### ISSUE TITLE
Unable to deploy via bitbucket pipelines or seed

### ISSUE THREAD

**Issue by Rohithzr** [serverless-stack/sst#2003]
So I have a requirement where I need to deploy via Bitbucket Pipelines.

My Stack
1. node 16
2. awscli
3. python3

Error

<details>

+ yarn run deploy-stage
yarn run v1.22.19
$ sst deploy --stage staging
Attention: SST now collects completely anonymous telemetry regarding usage. This is used to guide SST's roadmap.
You can learn more, including how to opt-out of this anonymous program, by heading over to:
https://docs.sst.dev/anonymous-telemetry
Using stage: staging
Preparing your SST app
Bootstrapping SST in the "us-east-1" region
Checking deploy status...
SSTBootstrap | REVIEW_IN_PROGRESS | AWS::CloudFormation::Stack | SSTBootstrap | User Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | SSTBootstrap | User Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::S3::Bucket | useast124D14E4B
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapversionE77EAB81
SSTBootstrap | CREATE_IN_PROGRESS | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapstackname4F02B8F9
SSTBootstrap | CREATE_IN_PROGRESS | AWS::S3::Bucket | useast124D14E4B | Resource creation Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092 | Resource creation Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapstackname4F02B8F9 | Resource creation Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapversionE77EAB81 | Resource creation Initiated
SSTBootstrap | CREATE_COMPLETE | AWS::SSM::Parameter | sstbootstrapstackname4F02B8F9
SSTBootstrap | CREATE_COMPLETE | AWS::SSM::Parameter | sstbootstrapversionE77EAB81
Checking deploy status...
Checking deploy status...
SSTBootstrap | CREATE_COMPLETE | AWS::IAM::Role | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
SSTBootstrap | CREATE_COMPLETE | AWS::S3::Bucket | useast124D14E4B
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapbucketname87B28FC9
SSTBootstrap | CREATE_IN_PROGRESS | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
SSTBootstrap | CREATE_IN_PROGRESS | AWS::S3::BucketPolicy | useast1PolicyE57DC004
SSTBootstrap | CREATE_IN_PROGRESS | AWS::S3::BucketPolicy | useast1PolicyE57DC004 | Resource creation Initiated
SSTBootstrap | CREATE_COMPLETE | AWS::S3::BucketPolicy | useast1PolicyE57DC004
SSTBootstrap | CREATE_IN_PROGRESS | AWS::SSM::Parameter | sstbootstrapbucketname87B28FC9 | Resource creation Initiated
SSTBootstrap | CREATE_IN_PROGRESS | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F | Resource creation Initiated
SSTBootstrap | CREATE_COMPLETE | AWS::SSM::Parameter | sstbootstrapbucketname87B28FC9
SSTBootstrap | CREATE_COMPLETE | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
SSTBootstrap | CREATE_IN_PROGRESS | Custom::S3AutoDeleteObjects | useast1AutoDeleteObjectsCustomResourceE0E6054B
Checking deploy status...
SSTBootstrap | CREATE_IN_PROGRESS | Custom::S3AutoDeleteObjects | useast1AutoDeleteObjectsCustomResourceE0E6054B | Resource creation Initiated
SSTBootstrap | CREATE_COMPLETE | Custom::S3AutoDeleteObjects | useast1AutoDeleteObjectsCustomResourceE0E6054B
SSTBootstrap | CREATE_COMPLETE | AWS::CloudFormation::Stack | SSTBootstrap
 ✅  SSTBootstrap
TypeError: Cannot read property 'replace' of undefined
    at Module.default (file:///opt/atlassian/pipelines/agent/build/.build/lib/index.js:105:45)
    at file:///opt/atlassian/pipelines/agent/build/.build/run.mjs:96:16
There was an error synthesizing your app.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</details>

Below is my pipeline file.

```
image: node:lts

pipelines:
  branches:
    default:
      - step:
          script:
            - echo "ignore"
    'staging':
      - parallel:
        - step:
            caches:
              - "node"
            script:
              - apt-get update && apt-get install -y python3-pip 
              - pip3 install -U awscli
              - export AWS_DEFAULT_REGION=us-east-1
              - export AWS_PROFILE=default
              - yarn install
              - yarn test
              - yarn run deploy-stage
```
