### ISSUE TITLE
StaticSite: Allow overwriting viewer request function

### ISSUE THREAD

**Issue by brad-hader-FHR** [serverless-stack/sst#2578]
PR #2564 introduced a viewer request function and there doesn't seem to be a way to remove it.  We have setups that use an Edge function on viewer request and CloudFront does not allow both a CloudFront function and an Edge function at the same time on viewer request or viewer response.

**Comment by jayair** [comment]
Let me check.

**Comment by fwang** [comment]
Hey @brad-hader-FHR, does overriding `functionAssociations` to `undefined` work for you?
```ts
const site = new StaticSite(stack, "mySite", {
  cdk: {
    distribution: {
      defaultBehavior: {
        functionAssociations: undefined,
      },
    },
  }
});
```

**Comment by brad-hader-FHR** [comment]
It did not.  First thing I tried.  Also, tried sending an empty array.

**Comment by fwang** [comment]
just gave this a try, seems to work.

### Without overriding `functionAssociations`
```ts
new StaticSite(stack, "mySite");
```
generated this block in the CloudFormation template.json
```yaml
  "SPADistributionA6A1EF89": {
   "Type": "AWS::CloudFront::Distribution",
   "Properties": {
    "DistributionConfig": {
     "DefaultCacheBehavior": {
      "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
      "Compress": true,
      "FunctionAssociations": [
       {
        "EventType": "viewer-request",
        "FunctionARN": {
         "Fn::GetAtt": [
          "SPACloudFrontFunctionDB066884",
          "FunctionARN"
         ]
        }
       }
      ],
      ...
     },
     ...
  },
```

### With `functionAssociations: undefined`
```ts
new StaticSite(stack, "mySite", {
  cdk: {
    distribution: {
      defaultBehavior: {
        functionAssociations: undefined,
      },
    },
  }
});
```
generated this block in the CloudFormation template.json
```yaml
  "SPADistributionA6A1EF89": {
   "Type": "AWS::CloudFront::Distribution",
   "Properties": {
    "DistributionConfig": {
     "DefaultCacheBehavior": {
      "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
      "Compress": true,
      "TargetOriginId": "devplaygroundStaticSiteStackSPADistributionOrigin1A6D5D7F3",
      "ViewerProtocolPolicy": "redirect-to-https"
     },
     ...
    },
    ...
  },
```
