### ISSUE TITLE
enforceSSL ignored on Bucket construct

### ISSUE THREAD

**Issue by berenddeboer** [serverless-stack/sst#3031]
I'm trying to set enforceSSL to true by default. This should emit a bucket policy in the output. Basic CDK example:
```ts
    new s3.Bucket(this, "Bucket", {
      enforceSSL: true,
    })

```

You'll get this as output:

```yaml
Resources:
  Bucket83908E77:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  BucketPolicyE9A3008A:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Bucket83908E77
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - Bucket83908E77
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - Bucket83908E77
                        - Arn
                    - /*
        Version: "2012-10-17"
```

However, SST never generates a bucket policy in the output. What's going on? Example SST:

```ts
  const stack = new Stack(await createApp(), "stack");
  new Bucket(stack, "Bucket", {
    cdk: {
      enforceSSL: true,
    },
  });
  let template = Template.fromStack(stack)
  console.log ("TEMPLATE", template)
  hasResource(stack, "AWS::S3::BucketPolicy", {
    Bucket: {
      Ref: "BucketD7FEB781",
    },
    PolicyDocument: {
      Statement: [
        {
          Action: "s3:*",
          Condition: {
            Bool: {
              "aws:SecureTransport": "false",
            },
          },
          Effect: "Deny",
        },
      ],
    },
  })
```

Output being:

```json
TEMPLATE Template {
  template: {
    Resources: {
      CustomResourceHandlerServiceRole41AEC181: [Object],
      CustomResourceHandlerE8FB56BA: [Object],
      BucketD7FEB781: [Object]
    },
    Parameters: { BootstrapVersion: [Object] },
    Rules: { CheckBootstrapVersion: [Object] }
  }
}
```

I completely fail to understand how this is possible. Somewhere this `enforceSSL` is removed it seems.
